
# Basic
basictitle: 沐澄
subtitle: 沐澄
## 底部状态栏描述
homeurl: https://lovemucheng.xyz
descriptionimg:
descriptionDate:
description: ICP备案号:鄂ICP备2022003408号

#以下暂未启用
# 头像里面的标题
##avatarTitle: 头像
# 首页里面的描述
##avatarDesc: 简介2
##greeting: 愿你所求皆如愿 所行化坦途 多喜乐 长安宁。

# 博客是否自动生成目录，false为不生成
enableToc: false

# 菜单栏
nav:
  - {title: 随笔, url: '/index',class: 'glyphicon glyphicon-pencil'}
  - {title: 标签, url: '/tags',class: 'glyphicon glyphicon-tags'}
  - {title: 视频, url: '/video',class: 'glyphicon glyphicon-cd'}
  - {title: 图册, url: '/images',class: 'glyphicon glyphicon-picture'}
  - {title: 友链, url: '/message',class: 'glyphicon glyphicon-heart-empty'}
  - {title: 关于, url: '/about',class: 'glyphicon glyphicon-paperclip'}
#  - {title: 开往, url: 'https://travellings.link',class: 'glyphicon glyphicon-modal-window'}
#- {title: 留言板, url: '/message',class: 'glyphicon glyphicon-envelope'}


friendList:
  - {title: 皮皮凛の小窝, intro: 永远相信美好的事情即将发生~。, imgUrl: 'https://cdn.jsdelivr.net/gh/AyagawaSeirin/Assets/img/logo.jpg',url: 'https://owomoe.net'}
  - {title: 月月月子喵, intro: 月子喵~。, imgUrl: 'https://haozi.moe/logo/base.ico',url: 'https://haozi.moe'}
  - {title: 汀彵の汐, intro: 好事多磨，浪漫不死。, imgUrl: 'https://q2.qlogo.cn/headimg_dl?dst_uin=2461306899&spec=100',url: 'https://www.izznan.cn'}
  - {title: 猫鱼的小窝, intro: 记录猫鱼生活的琐碎和分享喜欢的音乐。。, imgUrl: 'https://2cat.net/logos.jpg',url: 'https://2cat.net'}
  - {title: 崽崽, intro: 一个可爱崽, imgUrl: 'https://xll.cc/wj/photo/tx.jpg',url: 'https://xll.cc'}

friendtitle: 希望能能认识一些有趣的朋友~
friendintro:

#cdnurl

CDNUrl: http://youpaiyun.lovemucheng.xyz/images/emo/

# 畅言

APPID: eVAkskAETYgdDIOTy7zUKD1c-gzGzoHsz
APPSECRET: 0egMFFiWgJBUL9u73CperLb7


#permalink: /:categories/:year-:month-:day/:title
#permalink: /:year/:month/:title

# Format
highlighter: rouge
cover_color: clear

plugins:
  - jekyll-feed

# 分页
# 每页有几个项目
gems: [jekyll-paginate]
paginate: 7
paginate_path: "page:num"
