
# Basic
basictitle: 首页
subtitle: 简介1
## 底部状态栏描述
descriptionDate: 2021-10-19
description: 备案号
# 头像里面的标题
avatarTitle: 头像
# 首页里面的描述
avatarDesc: 简介2
greeting: 愿你所求皆如愿 所行化坦途 多喜乐 长安宁。

# 博客是否自动生成目录，false为不生成
enableToc: false

# 菜单栏
nav:
  - {title: 首页, description: about, url: '/',class: 'fa fa-home'}
  - {title: 标签, description: tag, url: '/',class: 'fa fa-tags'}
  - {title: 图册, description: tags, url: '/images',class: 'fa fa-picture-o'}
  #  - {title: 宝宝相薄, description: tags, url: '/star',class: 'fa fa-star'}
  - {title: 关于, description: comments, url: '/about',class: 'fa fa-lemon-o'}

# Format
highlighter: rouge
cover_color: clear

plugins:
  - jekyll-feed

# 分页
# 每页有几个项目
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"
