
# Basic
basictitle: 首页
subtitle: 简介1
## 底部状态栏描述
descriptionDate: 2021-10-19
description: 备案号
# 头像里面的标题
avatarTitle: 头像
# 首页里面的描述
avatarDesc: 简介2
greeting: 愿你所求皆如愿 所行化坦途 多喜乐 长安宁。

# 博客是否自动生成目录，false为不生成
enableToc: false

# 菜单栏
nav:
  - {title: 随笔, url: '/index',class: 'glyphicon glyphicon-pencil'}
  - {title: 标签, url: '/tags',class: 'glyphicon glyphicon-tags'}
  - {title: 视频, url: '/video',class: 'glyphicon glyphicon-cd'}
  - {title: 图册, url: '/images',class: 'glyphicon glyphicon-picture'}

permalink: /:categories/:year-:month-:day/:title

# Format
highlighter: rouge
cover_color: clear

plugins:
  - jekyll-feed

# 分页
# 每页有几个项目
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
